### ISSUE TITLE
Won't work with jest@20.1.0-delta.5

### ISSUE THREAD

**Issue by canda** [orta/vscode-jest#134]
### Environment

1. `node -v`: v8.2.1
2. `npm -v`: 5.3.0
4. `npm ls react-scripts` (if you haven’t ejected): empty

1. Operating system: macOS sierra

### Steps to Reproduce

`npm install jest@20.0`
Restart vscode and it works fine

`npm install jest@20.1.0-delta.5`
Restart vscode and it doesn't work

``

### Expected Behavior

Color dot should appear aside each it
Possible error message should display

### Actual Behavior

Non of these appear.
On devtools console appears this error
Cannot read property 'testRegex' of undefined: TypeError: Cannot read property 'testRegex' of undefined

**Comment by canda** [comment]
Tried to help running the project but with no luck :/
I have no experience developing vscode extensions, sorry about that
Cloned, yarn install, opened with vscode, F5 and nothing (no second window opened)
just this message on the debug console
![image](https://user-images.githubusercontent.com/1220263/29000783-158e3dc8-7a4d-11e7-9286-f3b61268dbd5.png)

If it's not something obvious / easy to fix, just focus on the issue, not on my lack of experience XD

**Comment by canda** [comment]
PS: I installed jest@20.1.0-delta.5 because 20.0 throws EMFILE error and was trying to avoid everyone having to run `brew install watchman`

**Comment by seanpoulter** [comment]
I'm closing the issue having been unable to reproduce this today. We're long past Jest 20.1.-delta.5.
